repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=140000']  # Set max file size to 30MB

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest  # Adjust this line if you're using a different command to run tests
        language: system
        pass_filenames: false

      - id: docs-build
        name: Build Sphinx docs (make html)
        entry: make -C docs html
        language: system
        pass_filenames: false
        files: ^docs/